
DROP TABLE IF EXISTS "Upvotes" CASCADE;
DROP TABLE IF EXISTS "Report" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "RouteAlternative" CASCADE;
DROP TABLE IF EXISTS "RouteSearch" CASCADE;
DROP TABLE IF EXISTS "RoutePointCache" CASCADE;


CREATE TABLE "Users" (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_auth uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  name varchar(100) NOT NULL,
  email varchar(100) NOT NULL UNIQUE,
  points int DEFAULT 0,
  avatar_url text
);

CREATE TABLE "Report" (
  report_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES "Users" (user_id),
  description text,
  photo_url text,
  latitude float NOT NULL,
  longitude float NOT NULL,
  category varchar(255) NOT NULL,
  address text,
  upvote_count int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE "Upvotes" (
    upvote_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES "Users"(user_id) ON DELETE CASCADE,
    report_id bigint NOT NULL REFERENCES "Report"(report_id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_report_upvote UNIQUE (user_id, report_id)
);

CREATE TABLE "RouteSearch" (
  search_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_point varchar(255) NOT NULL,
  end_point varchar(255) NOT NULL,
  mode varchar(50) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE "RoutePointCache" (
    point_cache_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude float NOT NULL,
    longitude float NOT NULL,
    walkability_score float,
    photo_url text,
    tree_count int,
    sidewalk_area float,
    is_residential_road boolean,
    heading int,
    detected_labels jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT routepointcache_lat_lng_unique UNIQUE (latitude, longitude)
);

CREATE TABLE "RouteAlternative" (
  route_alt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_id bigint NOT NULL REFERENCES "RouteSearch" (search_id) ON DELETE CASCADE,
  average_walkability_score float NOT NULL,
  overview_polyline text NOT NULL,
  point_ids bigint[]
);


CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public."Users" (user_id_auth, name, email, avatar_url)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.email,
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


CREATE POLICY "Allow authenticated uploads"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'avatars' AND
  auth.uid() = (storage.foldername(name))[1]::uuid
);

CREATE POLICY "Allow authenticated read access"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'avatars'
);

CREATE POLICY "Allow authenticated updates"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'avatars' AND
  auth.uid() = owner
);

CREATE POLICY "Allow authenticated deletes"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'avatars' AND
  auth.uid() = owner
);


CREATE POLICY "Allow authenticated report photo uploads"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'report-photos' );

CREATE POLICY "Allow public read access on report photos"
ON storage.objects FOR SELECT
USING ( bucket_id = 'report-photos' );
